# Generated by Django 6.1 on 2026-10-08 11:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_emailverificationtoken_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('kind', models.CharField(choices=[('charge', 'شارژ کیف پول'), ('payment', 'پرداخت بلیت'), ('refund', 'استرداد'), ('adjustment', 'اصلاح دستی')], max_length=20, verbose_name='نوع تراکنش')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='مبلغ (مثبت = واریز، منفی = برداشت)')),
                ('balance_before', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='موجودی قبل')),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='موجودی بعد')),
                ('reference', models.CharField(blank=True, db_index=True, max_length=40, verbose_name='کد رزرو مرتبط')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='توضیح')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wallet_transactions', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'تراکنش کیف پول',
                'verbose_name_plural': 'تراکنش\u200cهای کیف پول',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='accounts_wa_user_id_dbce41_idx')],
            },
        ),
    ]
