# Generated by Django 6.1 on 2026-08-19 07:34

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام شرکت هواپیمایی')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='airlines/logos/', verbose_name='لوگو')),
            ],
            options={
                'verbose_name': 'شرکت هواپیمایی',
                'verbose_name_plural': 'شرکت\u200cهای هواپیمایی',
            },
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('name', models.CharField(max_length=120, verbose_name='نام فرودگاه')),
                ('city', models.CharField(db_index=True, max_length=80, verbose_name='شهر')),
                ('iata_code', models.CharField(max_length=3, unique=True, verbose_name='کد یاتا (IATA)')),
            ],
            options={
                'verbose_name': 'فرودگاه',
                'verbose_name_plural': 'فرودگاه\u200cها',
                'ordering': ['city', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arriving_routes', to='flights.airport', verbose_name='مقصد')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departing_routes', to='flights.airport', verbose_name='مبدا')),
            ],
            options={
                'verbose_name': 'مسیر پروازی',
                'verbose_name_plural': 'مسیرهای پروازی',
            },
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('flight_number', models.CharField(max_length=20, unique=True, verbose_name='شماره پرواز')),
                ('airplane_type', models.CharField(max_length=60, verbose_name='نوع هواپیما')),
                ('departure_datetime', models.DateTimeField(db_index=True, verbose_name='تاریخ و ساعت حرکت')),
                ('arrival_datetime', models.DateTimeField(verbose_name='تاریخ و ساعت رسیدن')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='قیمت پایه (تومان)')),
                ('cancellation_penalty_percent', models.PositiveSmallIntegerField(default=20, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='درصد جریمه کنسلی')),
                ('status', models.CharField(choices=[('scheduled', 'برنامه\u200cریزی شده'), ('active', 'در حال انجام'), ('completed', 'انجام شده'), ('cancelled', 'لغو شده')], default='scheduled', max_length=15, verbose_name='وضعیت پرواز')),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flights', to='flights.airline', verbose_name='ایرلاین')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flights', to='flights.route', verbose_name='مسیر')),
            ],
            options={
                'verbose_name': 'پرواز',
                'verbose_name_plural': 'پروازها',
                'ordering': ['departure_datetime'],
            },
        ),
        migrations.CreateModel(
            name='SeatClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('class_type', models.CharField(choices=[('economy', 'اکونومی'), ('business', 'بیزینس'), ('first', 'فرست کلاس')], max_length=15, verbose_name='کلاس صندلی')),
                ('price_multiplier', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('1.00'))], verbose_name='ضریب قیمت')),
                ('capacity', models.PositiveIntegerField(verbose_name='ظرفیت کل')),
                ('available_seats', models.PositiveIntegerField(verbose_name='صندلی\u200cهای موجود')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_classes', to='flights.flight', verbose_name='پرواز')),
            ],
            options={
                'verbose_name': 'کلاس پروازی صندلی',
                'verbose_name_plural': 'کلاس\u200cهای پروازی صندلی',
            },
        ),
        migrations.AddConstraint(
            model_name='route',
            constraint=models.UniqueConstraint(fields=('origin', 'destination'), name='unique_route_pair'),
        ),
        migrations.AddConstraint(
            model_name='route',
            constraint=models.CheckConstraint(condition=models.Q(('origin', models.F('destination')), _negated=True), name='prevent_self_route'),
        ),
        migrations.AddConstraint(
            model_name='seatclass',
            constraint=models.UniqueConstraint(fields=('flight', 'class_type'), name='unique_flight_seat_class'),
        ),
    ]
