# Generated by Django 6.1 on 2026-08-19 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='flight',
            index=models.Index(fields=['route', 'departure_datetime'], name='flights_fli_route_i_94ab38_idx'),
        ),
        migrations.AddIndex(
            model_name='flight',
            index=models.Index(fields=['status'], name='flights_fli_status_e6e528_idx'),
        ),
        migrations.AddConstraint(
            model_name='flight',
            constraint=models.CheckConstraint(condition=models.Q(('arrival_datetime__gt', models.F('departure_datetime'))), name='arrival_after_departure'),
        ),
        migrations.AddConstraint(
            model_name='seatclass',
            constraint=models.CheckConstraint(condition=models.Q(('available_seats__lte', models.F('capacity'))), name='available_seats_lte_capacity'),
        ),
    ]
