# Generated by Django 6.1 on 2026-08-20 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_flight_flights_fli_route_i_94ab38_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='airplane_type',
            field=models.CharField(choices=[('Airbus A320', 'ایرباس A320'), ('Airbus A330', 'ایرباس A330'), ('Boeing 737', 'بوئینگ 737'), ('Boeing 777', 'بوئینگ 777'), ('Fokker 100', 'فوکر 100'), ('ATR 72', 'ای\u200cتی\u200cآر 72')], default='Airbus A320', max_length=60, verbose_name='نوع هواپیما'),
        ),
    ]
