# Generated by Django 6.1 on 2026-08-21 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_alter_flight_airplane_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='airplane_type',
            field=models.CharField(max_length=60, verbose_name='نوع هواپیما'),
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('row_number', models.PositiveSmallIntegerField(verbose_name='شماره ردیف')),
                ('column_letter', models.CharField(max_length=1, verbose_name='حرف ستون')),
                ('is_available', models.BooleanField(default=True, verbose_name='در دسترس')),
                ('seat_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='flights.seatclass', verbose_name='کلاس صندلی')),
            ],
            options={
                'verbose_name': 'صندلی',
                'verbose_name_plural': 'صندلی\u200cها',
                'ordering': ['row_number', 'column_letter'],
                'constraints': [models.UniqueConstraint(fields=('seat_class', 'row_number', 'column_letter'), name='unique_seat_per_class')],
            },
        ),
    ]
