# Generated by Django 6.1 on 2026-08-22 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0004_alter_flight_airplane_type_seat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='airplane_type',
            field=models.CharField(choices=[('a320', 'ایرباس A320'), ('a321', 'ایرباس A321'), ('a330', 'ایرباس A330'), ('b737', 'بوئینگ 737'), ('b777', 'بوئینگ 777'), ('b787', 'بوئینگ 787 دریم\u200cلاینر'), ('atr72', 'ATR 72'), ('md88', 'مک\u200cدانل داگلاس MD-88'), ('fokker100', 'فوکر 100')], max_length=15, verbose_name='نوع هواپیما'),
        ),
    ]
