# Generated by Django 6.1 on 2026-08-23 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0005_alter_flight_airplane_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airline',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='airport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='route',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='seatclass',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد'),
        ),
    ]
