# Generated by Django 6.1 on 2026-09-27 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0006_alter_airline_created_at_alter_airport_created_at_and_more'),
    ]

    operations = [
        migrations.AlterConstraint(
            model_name='flight',
            name='arrival_after_departure',
            constraint=models.CheckConstraint(condition=models.Q(('arrival_datetime__gt', models.F('departure_datetime'))), name='arrival_after_departure', violation_error_message='زمان رسیدن باید بعد از زمان حرکت باشد.'),
        ),
        migrations.AlterConstraint(
            model_name='route',
            name='unique_route_pair',
            constraint=models.UniqueConstraint(fields=('origin', 'destination'), name='unique_route_pair', violation_error_message='این مسیر (مبدا و مقصد) قبلاً ثبت شده است.'),
        ),
        migrations.AlterConstraint(
            model_name='route',
            name='prevent_self_route',
            constraint=models.CheckConstraint(condition=models.Q(('origin', models.F('destination')), _negated=True), name='prevent_self_route', violation_error_message='مبدا و مقصد نمی\u200cتوانند یکسان باشند.'),
        ),
        migrations.AlterConstraint(
            model_name='seatclass',
            name='unique_flight_seat_class',
            constraint=models.UniqueConstraint(fields=('flight', 'class_type'), name='unique_flight_seat_class', violation_error_message='این کلاس صندلی قبلاً برای این پرواز تعریف شده است.'),
        ),
        migrations.AlterConstraint(
            model_name='seatclass',
            name='available_seats_lte_capacity',
            constraint=models.CheckConstraint(condition=models.Q(('available_seats__lte', models.F('capacity'))), name='available_seats_lte_capacity', violation_error_message='صندلی\u200cهای موجود نمی\u200cتواند بیشتر از ظرفیت کل باشد.'),
        ),
    ]
