# Generated by Django 6.1 on 2026-08-19 07:34

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flights', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('booking_reference', models.CharField(editable=False, max_length=10, unique=True, verbose_name='شناسه رزرو (PNR)')),
                ('seats_count', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='تعداد صندلی')),
                ('total_paid_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='مبلغ پرداخت\u200cشده (تومان)')),
                ('refund_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='مبلغ استردادشده (تومان)')),
                ('status', models.CharField(choices=[('reserved', 'رزرو شده (قطعی)'), ('cancelled', 'کنسل شده')], default='reserved', max_length=15, verbose_name='وضعیت رزرو')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ و ساعت کنسلی')),
                ('seat_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='flights.seatclass', verbose_name='کلاس صندلی')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to=settings.AUTH_USER_MODEL, verbose_name='کاربر رزروکننده')),
            ],
            options={
                'verbose_name': 'رزرو',
                'verbose_name_plural': 'رزروها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('first_name', models.CharField(max_length=60, verbose_name='نام')),
                ('last_name', models.CharField(max_length=60, verbose_name='نام خانوادگی')),
                ('national_id', models.CharField(max_length=10, verbose_name='کد ملی')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passengers', to='tickets.reservation', verbose_name='رزرو مربوطه')),
            ],
            options={
                'verbose_name': 'مشخصات مسافر',
                'verbose_name_plural': 'مشخصات مسافران',
            },
        ),
    ]
