# Generated by Django 6.1 on 2026-08-19 08:08

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_flight_flights_fli_route_i_94ab38_idx_and_more'),
        ('tickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='national_id',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'کد ملی باید دقیقاً ۱۰ رقم باشد')], verbose_name='کد ملی'),
        ),
        migrations.AlterUniqueTogether(
            name='passenger',
            unique_together={('reservation', 'national_id')},
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['user', 'status'], name='tickets_res_user_id_1037cf_idx'),
        ),
    ]
