# Generated by Django 6.1 on 2026-08-21 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0004_alter_flight_airplane_type_seat'),
        ('tickets', '0002_alter_passenger_national_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationSeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_seats', to='tickets.reservation', verbose_name='رزرو')),
                ('seat', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='reservation_seat', to='flights.seat', verbose_name='صندلی')),
            ],
            options={
                'verbose_name': 'صندلی رزروشده',
                'verbose_name_plural': 'صندلی\u200cهای رزروشده',
            },
        ),
    ]
