# Generated by Django 6.1 on 2026-10-03 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_alter_passenger_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'در انتظار پرداخت'), ('reserved', 'رزرو شده (قطعی)'), ('cancelled', 'کنسل شده')], default='reserved', max_length=20, verbose_name='وضعیت رزرو'),
        ),
    ]
