# Generated by Django 6.1 on 2026-10-03 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_alter_reservation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='payment_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
