# Generated by Django 6.1 on 2026-10-06 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_reservation_payment_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ و ساعت پرداخت'),
        ),
    ]
