# Generated by Django 6.1 on 2026-10-07 10:34

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0007_alter_flight_arrival_after_departure_and_more'),
        ('tickets', '0007_reservation_paid_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='cancellation_reason',
            field=models.CharField(blank=True, choices=[('user', 'لغو توسط کاربر'), ('timeout', 'پایان مهلت پرداخت'), ('flight_cancelled', 'لغو پرواز')], default='', max_length=20, verbose_name='دلیل کنسلی'),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='national_id',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^[0-9]{10}\\Z', 'کد ملی باید دقیقاً ۱۰ رقم (انگلیسی) باشد')], verbose_name='کد ملی'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='payment_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='مهلت پرداخت'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'در انتظار پرداخت'), ('reserved', 'رزرو شده (قطعی)'), ('cancelled', 'کنسل شده')], default='pending_payment', max_length=20, verbose_name='وضعیت رزرو'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='total_paid_price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='مبلغ رزرو/پرداخت\u200cشده (تومان)'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['status', 'payment_expires_at'], name='tickets_res_status_340c6c_idx'),
        ),
    ]
